### ISSUE TITLE
WhatsApp-web.js suddenly logs out on restore session with no reason

### ISSUE THREAD

**Issue by yairmelamed** [pedroslopez/whatsapp-web.js#2740] opened 2024-01-21 20:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

WhatsApp-web.js suddenly logs out on session restore with no reason and asks me to rescan the qr code..

### Expected behavior

Restore WhatsApp Session..

### Steps to Reproduce the Bug or Issue

It happens sometimes not every session restore..

### Relevant Code

  authStrategy: new LocalAuth({
                clientId: sessionId
            }

### Browser Type

Chromium

### WhatsApp Account Type

WhatsApp Business

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

ubuntu

**Comment by alechkos** [comment] 2024-01-21 20:57
Duplicate of #2164

**Closed by alechkos** 2024-01-21 20:57 UTC
Labels: bug
