### ISSUE TITLE
RemoteAuth not working

### ISSUE THREAD

**Issue by AryaAnish121** [pedroslopez/whatsapp-web.js#2667] opened 2023-12-06 17:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I am using the following code to test out remote authentication in my project):

```js
require("dotenv").config();
const { Client, RemoteAuth } = require("whatsapp-web.js");

// Require database
const { MongoStore } = require("wwebjs-mongo");
const mongoose = require("mongoose");

// Load the session data
mongoose.connect(process.env.MONGODB_URI).then(() => {
    const store = new MongoStore({ mongoose: mongoose });
    const client = new Client({
        puppeteer: {
            headless: false,
        },
        authStrategy: new RemoteAuth({
            store: store,
            backupSyncIntervalMs: 60000,
        }),
    });

    client.initialize();
});
```

What I notice is that even when the session successfully (after scanning the qr code) gets saved to mongodb, I am still required to scan the qr code and the session is not retrieved. I started debugging and found out that the problem lay in the compression method which compressed and empty 'Default' folder and saved it to mongo db using wwebjs-mongo. I also tried to implement my own method by saving and compressing the session after closing the browser (as compressing and accessing session files while the browser is running results in an error; files are simultaneously being used) but now the problem was that instead of using the old session it created a new session file (in .wwebjs_auth -> session -> default -> sessions folder)

Is there any other working example. I have refered to other methods such as downgrading node.js and the methods suggested in [#2530](https://github.com/pedroslopez/whatsapp-web.js/issues/2530#issue-1909263085). But none seem to work as the problem lies in compression and saving and restoring the session.

Note: I wait for the session to be saved to mongo db.

### Expected behavior

the session gets restored

### Steps to Reproduce the Bug or Issue

1. connect to mongodb 
2. run the above code taken from example

### Relevant Code

```js
require("dotenv").config();
const { Client, RemoteAuth } = require("whatsapp-web.js");

// Require database
const { MongoStore } = require("wwebjs-mongo");
const mongoose = require("mongoose");

// Load the session data
mongoose.connect(process.env.MONGODB_URI).then(() => {
    const store = new MongoStore({ mongoose: mongoose });
    const client = new Client({
        puppeteer: {
            headless: false,
        },
        authStrategy: new RemoteAuth({
            store: store,
            backupSyncIntervalMs: 60000,
        }),
    });

    client.initialize();
});
```

### Browser Type

Chromium

### WhatsApp Account Type

Standard

### Does your WhatsApp account have multidevice enabled?

Yes, I am using Multi Device

### Environment

Node.js Version: 18.18.2
whatsapp-web.js: 1.23.0
wwebjs-mongo: 1.1.0

**Comment by alechkos** [comment] 2023-12-06 19:44
The issue is not related to the library but to the [wwebjs-mongo](https://github.com/jtouris/wwebjs-mongo)
Duplicate of #2631

**Closed by alechkos** 2023-12-06 19:44 UTC
Labels: bug

**Comment by alechkos** [comment] 2023-12-06 19:45
Duplicate of #2631
